// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PasswordItemsColumns holds the columns for the "password_items" table.
	PasswordItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString, Size: 1024},
		{Name: "site_name", Type: field.TypeString},
		{Name: "username", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PasswordItemsTable holds the schema information for the "password_items" table.
	PasswordItemsTable = &schema.Table{
		Name:       "password_items",
		Columns:    PasswordItemsColumns,
		PrimaryKey: []*schema.Column{PasswordItemsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PasswordItemsTable,
	}
)

func init() {
}
