// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/riadafridishibly/vault-app/ent/migrate"

	"github.com/riadafridishibly/vault-app/ent/file"
	"github.com/riadafridishibly/vault-app/ent/key"
	"github.com/riadafridishibly/vault-app/ent/masterpassword"
	"github.com/riadafridishibly/vault-app/ent/passworditem"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// File is the client for interacting with the File builders.
	File *FileClient
	// Key is the client for interacting with the Key builders.
	Key *KeyClient
	// MasterPassword is the client for interacting with the MasterPassword builders.
	MasterPassword *MasterPasswordClient
	// PasswordItem is the client for interacting with the PasswordItem builders.
	PasswordItem *PasswordItemClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.File = NewFileClient(c.config)
	c.Key = NewKeyClient(c.config)
	c.MasterPassword = NewMasterPasswordClient(c.config)
	c.PasswordItem = NewPasswordItemClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		File:           NewFileClient(cfg),
		Key:            NewKeyClient(cfg),
		MasterPassword: NewMasterPasswordClient(cfg),
		PasswordItem:   NewPasswordItemClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		File:           NewFileClient(cfg),
		Key:            NewKeyClient(cfg),
		MasterPassword: NewMasterPasswordClient(cfg),
		PasswordItem:   NewPasswordItemClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		File.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.File.Use(hooks...)
	c.Key.Use(hooks...)
	c.MasterPassword.Use(hooks...)
	c.PasswordItem.Use(hooks...)
}

// FileClient is a client for the File schema.
type FileClient struct {
	config
}

// NewFileClient returns a client for the File from the given config.
func NewFileClient(c config) *FileClient {
	return &FileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `file.Hooks(f(g(h())))`.
func (c *FileClient) Use(hooks ...Hook) {
	c.hooks.File = append(c.hooks.File, hooks...)
}

// Create returns a builder for creating a File entity.
func (c *FileClient) Create() *FileCreate {
	mutation := newFileMutation(c.config, OpCreate)
	return &FileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of File entities.
func (c *FileClient) CreateBulk(builders ...*FileCreate) *FileCreateBulk {
	return &FileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for File.
func (c *FileClient) Update() *FileUpdate {
	mutation := newFileMutation(c.config, OpUpdate)
	return &FileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FileClient) UpdateOne(f *File) *FileUpdateOne {
	mutation := newFileMutation(c.config, OpUpdateOne, withFile(f))
	return &FileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FileClient) UpdateOneID(id int) *FileUpdateOne {
	mutation := newFileMutation(c.config, OpUpdateOne, withFileID(id))
	return &FileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for File.
func (c *FileClient) Delete() *FileDelete {
	mutation := newFileMutation(c.config, OpDelete)
	return &FileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FileClient) DeleteOne(f *File) *FileDeleteOne {
	return c.DeleteOneID(f.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FileClient) DeleteOneID(id int) *FileDeleteOne {
	builder := c.Delete().Where(file.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FileDeleteOne{builder}
}

// Query returns a query builder for File.
func (c *FileClient) Query() *FileQuery {
	return &FileQuery{
		config: c.config,
	}
}

// Get returns a File entity by its id.
func (c *FileClient) Get(ctx context.Context, id int) (*File, error) {
	return c.Query().Where(file.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FileClient) GetX(ctx context.Context, id int) *File {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FileClient) Hooks() []Hook {
	return c.hooks.File
}

// KeyClient is a client for the Key schema.
type KeyClient struct {
	config
}

// NewKeyClient returns a client for the Key from the given config.
func NewKeyClient(c config) *KeyClient {
	return &KeyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `key.Hooks(f(g(h())))`.
func (c *KeyClient) Use(hooks ...Hook) {
	c.hooks.Key = append(c.hooks.Key, hooks...)
}

// Create returns a builder for creating a Key entity.
func (c *KeyClient) Create() *KeyCreate {
	mutation := newKeyMutation(c.config, OpCreate)
	return &KeyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Key entities.
func (c *KeyClient) CreateBulk(builders ...*KeyCreate) *KeyCreateBulk {
	return &KeyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Key.
func (c *KeyClient) Update() *KeyUpdate {
	mutation := newKeyMutation(c.config, OpUpdate)
	return &KeyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *KeyClient) UpdateOne(k *Key) *KeyUpdateOne {
	mutation := newKeyMutation(c.config, OpUpdateOne, withKey(k))
	return &KeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *KeyClient) UpdateOneID(id int) *KeyUpdateOne {
	mutation := newKeyMutation(c.config, OpUpdateOne, withKeyID(id))
	return &KeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Key.
func (c *KeyClient) Delete() *KeyDelete {
	mutation := newKeyMutation(c.config, OpDelete)
	return &KeyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *KeyClient) DeleteOne(k *Key) *KeyDeleteOne {
	return c.DeleteOneID(k.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *KeyClient) DeleteOneID(id int) *KeyDeleteOne {
	builder := c.Delete().Where(key.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &KeyDeleteOne{builder}
}

// Query returns a query builder for Key.
func (c *KeyClient) Query() *KeyQuery {
	return &KeyQuery{
		config: c.config,
	}
}

// Get returns a Key entity by its id.
func (c *KeyClient) Get(ctx context.Context, id int) (*Key, error) {
	return c.Query().Where(key.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *KeyClient) GetX(ctx context.Context, id int) *Key {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *KeyClient) Hooks() []Hook {
	return c.hooks.Key
}

// MasterPasswordClient is a client for the MasterPassword schema.
type MasterPasswordClient struct {
	config
}

// NewMasterPasswordClient returns a client for the MasterPassword from the given config.
func NewMasterPasswordClient(c config) *MasterPasswordClient {
	return &MasterPasswordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `masterpassword.Hooks(f(g(h())))`.
func (c *MasterPasswordClient) Use(hooks ...Hook) {
	c.hooks.MasterPassword = append(c.hooks.MasterPassword, hooks...)
}

// Create returns a builder for creating a MasterPassword entity.
func (c *MasterPasswordClient) Create() *MasterPasswordCreate {
	mutation := newMasterPasswordMutation(c.config, OpCreate)
	return &MasterPasswordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MasterPassword entities.
func (c *MasterPasswordClient) CreateBulk(builders ...*MasterPasswordCreate) *MasterPasswordCreateBulk {
	return &MasterPasswordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MasterPassword.
func (c *MasterPasswordClient) Update() *MasterPasswordUpdate {
	mutation := newMasterPasswordMutation(c.config, OpUpdate)
	return &MasterPasswordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MasterPasswordClient) UpdateOne(mp *MasterPassword) *MasterPasswordUpdateOne {
	mutation := newMasterPasswordMutation(c.config, OpUpdateOne, withMasterPassword(mp))
	return &MasterPasswordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MasterPasswordClient) UpdateOneID(id int) *MasterPasswordUpdateOne {
	mutation := newMasterPasswordMutation(c.config, OpUpdateOne, withMasterPasswordID(id))
	return &MasterPasswordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MasterPassword.
func (c *MasterPasswordClient) Delete() *MasterPasswordDelete {
	mutation := newMasterPasswordMutation(c.config, OpDelete)
	return &MasterPasswordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MasterPasswordClient) DeleteOne(mp *MasterPassword) *MasterPasswordDeleteOne {
	return c.DeleteOneID(mp.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MasterPasswordClient) DeleteOneID(id int) *MasterPasswordDeleteOne {
	builder := c.Delete().Where(masterpassword.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MasterPasswordDeleteOne{builder}
}

// Query returns a query builder for MasterPassword.
func (c *MasterPasswordClient) Query() *MasterPasswordQuery {
	return &MasterPasswordQuery{
		config: c.config,
	}
}

// Get returns a MasterPassword entity by its id.
func (c *MasterPasswordClient) Get(ctx context.Context, id int) (*MasterPassword, error) {
	return c.Query().Where(masterpassword.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MasterPasswordClient) GetX(ctx context.Context, id int) *MasterPassword {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MasterPasswordClient) Hooks() []Hook {
	return c.hooks.MasterPassword
}

// PasswordItemClient is a client for the PasswordItem schema.
type PasswordItemClient struct {
	config
}

// NewPasswordItemClient returns a client for the PasswordItem from the given config.
func NewPasswordItemClient(c config) *PasswordItemClient {
	return &PasswordItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `passworditem.Hooks(f(g(h())))`.
func (c *PasswordItemClient) Use(hooks ...Hook) {
	c.hooks.PasswordItem = append(c.hooks.PasswordItem, hooks...)
}

// Create returns a builder for creating a PasswordItem entity.
func (c *PasswordItemClient) Create() *PasswordItemCreate {
	mutation := newPasswordItemMutation(c.config, OpCreate)
	return &PasswordItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PasswordItem entities.
func (c *PasswordItemClient) CreateBulk(builders ...*PasswordItemCreate) *PasswordItemCreateBulk {
	return &PasswordItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PasswordItem.
func (c *PasswordItemClient) Update() *PasswordItemUpdate {
	mutation := newPasswordItemMutation(c.config, OpUpdate)
	return &PasswordItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PasswordItemClient) UpdateOne(pi *PasswordItem) *PasswordItemUpdateOne {
	mutation := newPasswordItemMutation(c.config, OpUpdateOne, withPasswordItem(pi))
	return &PasswordItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PasswordItemClient) UpdateOneID(id int) *PasswordItemUpdateOne {
	mutation := newPasswordItemMutation(c.config, OpUpdateOne, withPasswordItemID(id))
	return &PasswordItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PasswordItem.
func (c *PasswordItemClient) Delete() *PasswordItemDelete {
	mutation := newPasswordItemMutation(c.config, OpDelete)
	return &PasswordItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PasswordItemClient) DeleteOne(pi *PasswordItem) *PasswordItemDeleteOne {
	return c.DeleteOneID(pi.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PasswordItemClient) DeleteOneID(id int) *PasswordItemDeleteOne {
	builder := c.Delete().Where(passworditem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PasswordItemDeleteOne{builder}
}

// Query returns a query builder for PasswordItem.
func (c *PasswordItemClient) Query() *PasswordItemQuery {
	return &PasswordItemQuery{
		config: c.config,
	}
}

// Get returns a PasswordItem entity by its id.
func (c *PasswordItemClient) Get(ctx context.Context, id int) (*PasswordItem, error) {
	return c.Query().Where(passworditem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PasswordItemClient) GetX(ctx context.Context, id int) *PasswordItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PasswordItemClient) Hooks() []Hook {
	return c.hooks.PasswordItem
}
