// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/riadafridishibly/vault-app/ent/masterpassword"
)

// MasterPasswordCreate is the builder for creating a MasterPassword entity.
type MasterPasswordCreate struct {
	config
	mutation *MasterPasswordMutation
	hooks    []Hook
}

// SetPasswordHash sets the "password_hash" field.
func (mpc *MasterPasswordCreate) SetPasswordHash(s string) *MasterPasswordCreate {
	mpc.mutation.SetPasswordHash(s)
	return mpc
}

// Mutation returns the MasterPasswordMutation object of the builder.
func (mpc *MasterPasswordCreate) Mutation() *MasterPasswordMutation {
	return mpc.mutation
}

// Save creates the MasterPassword in the database.
func (mpc *MasterPasswordCreate) Save(ctx context.Context) (*MasterPassword, error) {
	var (
		err  error
		node *MasterPassword
	)
	if len(mpc.hooks) == 0 {
		if err = mpc.check(); err != nil {
			return nil, err
		}
		node, err = mpc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MasterPasswordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mpc.check(); err != nil {
				return nil, err
			}
			mpc.mutation = mutation
			if node, err = mpc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(mpc.hooks) - 1; i >= 0; i-- {
			if mpc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mpc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, mpc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*MasterPassword)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from MasterPasswordMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mpc *MasterPasswordCreate) SaveX(ctx context.Context) *MasterPassword {
	v, err := mpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mpc *MasterPasswordCreate) Exec(ctx context.Context) error {
	_, err := mpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpc *MasterPasswordCreate) ExecX(ctx context.Context) {
	if err := mpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mpc *MasterPasswordCreate) check() error {
	if _, ok := mpc.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "MasterPassword.password_hash"`)}
	}
	if v, ok := mpc.mutation.PasswordHash(); ok {
		if err := masterpassword.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "MasterPassword.password_hash": %w`, err)}
		}
	}
	return nil
}

func (mpc *MasterPasswordCreate) sqlSave(ctx context.Context) (*MasterPassword, error) {
	_node, _spec := mpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (mpc *MasterPasswordCreate) createSpec() (*MasterPassword, *sqlgraph.CreateSpec) {
	var (
		_node = &MasterPassword{config: mpc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: masterpassword.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: masterpassword.FieldID,
			},
		}
	)
	if value, ok := mpc.mutation.PasswordHash(); ok {
		_spec.SetField(masterpassword.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	return _node, _spec
}

// MasterPasswordCreateBulk is the builder for creating many MasterPassword entities in bulk.
type MasterPasswordCreateBulk struct {
	config
	builders []*MasterPasswordCreate
}

// Save creates the MasterPassword entities in the database.
func (mpcb *MasterPasswordCreateBulk) Save(ctx context.Context) ([]*MasterPassword, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mpcb.builders))
	nodes := make([]*MasterPassword, len(mpcb.builders))
	mutators := make([]Mutator, len(mpcb.builders))
	for i := range mpcb.builders {
		func(i int, root context.Context) {
			builder := mpcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MasterPasswordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mpcb *MasterPasswordCreateBulk) SaveX(ctx context.Context) []*MasterPassword {
	v, err := mpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mpcb *MasterPasswordCreateBulk) Exec(ctx context.Context) error {
	_, err := mpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpcb *MasterPasswordCreateBulk) ExecX(ctx context.Context) {
	if err := mpcb.Exec(ctx); err != nil {
		panic(err)
	}
}
