// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/riadafridishibly/vault-app/ent/masterpassword"
	"github.com/riadafridishibly/vault-app/ent/predicate"
)

// MasterPasswordUpdate is the builder for updating MasterPassword entities.
type MasterPasswordUpdate struct {
	config
	hooks    []Hook
	mutation *MasterPasswordMutation
}

// Where appends a list predicates to the MasterPasswordUpdate builder.
func (mpu *MasterPasswordUpdate) Where(ps ...predicate.MasterPassword) *MasterPasswordUpdate {
	mpu.mutation.Where(ps...)
	return mpu
}

// SetPasswordHash sets the "password_hash" field.
func (mpu *MasterPasswordUpdate) SetPasswordHash(s string) *MasterPasswordUpdate {
	mpu.mutation.SetPasswordHash(s)
	return mpu
}

// Mutation returns the MasterPasswordMutation object of the builder.
func (mpu *MasterPasswordUpdate) Mutation() *MasterPasswordMutation {
	return mpu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mpu *MasterPasswordUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mpu.hooks) == 0 {
		if err = mpu.check(); err != nil {
			return 0, err
		}
		affected, err = mpu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MasterPasswordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mpu.check(); err != nil {
				return 0, err
			}
			mpu.mutation = mutation
			affected, err = mpu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mpu.hooks) - 1; i >= 0; i-- {
			if mpu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mpu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mpu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mpu *MasterPasswordUpdate) SaveX(ctx context.Context) int {
	affected, err := mpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mpu *MasterPasswordUpdate) Exec(ctx context.Context) error {
	_, err := mpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpu *MasterPasswordUpdate) ExecX(ctx context.Context) {
	if err := mpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mpu *MasterPasswordUpdate) check() error {
	if v, ok := mpu.mutation.PasswordHash(); ok {
		if err := masterpassword.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "MasterPassword.password_hash": %w`, err)}
		}
	}
	return nil
}

func (mpu *MasterPasswordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   masterpassword.Table,
			Columns: masterpassword.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: masterpassword.FieldID,
			},
		},
	}
	if ps := mpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mpu.mutation.PasswordHash(); ok {
		_spec.SetField(masterpassword.FieldPasswordHash, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{masterpassword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// MasterPasswordUpdateOne is the builder for updating a single MasterPassword entity.
type MasterPasswordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MasterPasswordMutation
}

// SetPasswordHash sets the "password_hash" field.
func (mpuo *MasterPasswordUpdateOne) SetPasswordHash(s string) *MasterPasswordUpdateOne {
	mpuo.mutation.SetPasswordHash(s)
	return mpuo
}

// Mutation returns the MasterPasswordMutation object of the builder.
func (mpuo *MasterPasswordUpdateOne) Mutation() *MasterPasswordMutation {
	return mpuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mpuo *MasterPasswordUpdateOne) Select(field string, fields ...string) *MasterPasswordUpdateOne {
	mpuo.fields = append([]string{field}, fields...)
	return mpuo
}

// Save executes the query and returns the updated MasterPassword entity.
func (mpuo *MasterPasswordUpdateOne) Save(ctx context.Context) (*MasterPassword, error) {
	var (
		err  error
		node *MasterPassword
	)
	if len(mpuo.hooks) == 0 {
		if err = mpuo.check(); err != nil {
			return nil, err
		}
		node, err = mpuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MasterPasswordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mpuo.check(); err != nil {
				return nil, err
			}
			mpuo.mutation = mutation
			node, err = mpuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(mpuo.hooks) - 1; i >= 0; i-- {
			if mpuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mpuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, mpuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*MasterPassword)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from MasterPasswordMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (mpuo *MasterPasswordUpdateOne) SaveX(ctx context.Context) *MasterPassword {
	node, err := mpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mpuo *MasterPasswordUpdateOne) Exec(ctx context.Context) error {
	_, err := mpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpuo *MasterPasswordUpdateOne) ExecX(ctx context.Context) {
	if err := mpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mpuo *MasterPasswordUpdateOne) check() error {
	if v, ok := mpuo.mutation.PasswordHash(); ok {
		if err := masterpassword.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "MasterPassword.password_hash": %w`, err)}
		}
	}
	return nil
}

func (mpuo *MasterPasswordUpdateOne) sqlSave(ctx context.Context) (_node *MasterPassword, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   masterpassword.Table,
			Columns: masterpassword.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: masterpassword.FieldID,
			},
		},
	}
	id, ok := mpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MasterPassword.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, masterpassword.FieldID)
		for _, f := range fields {
			if !masterpassword.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != masterpassword.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mpuo.mutation.PasswordHash(); ok {
		_spec.SetField(masterpassword.FieldPasswordHash, field.TypeString, value)
	}
	_node = &MasterPassword{config: mpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{masterpassword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
