// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/riadafridishibly/vault-app/ent/passworditem"
	"github.com/riadafridishibly/vault-app/ent/predicate"
)

// PasswordItemUpdate is the builder for updating PasswordItem entities.
type PasswordItemUpdate struct {
	config
	hooks    []Hook
	mutation *PasswordItemMutation
}

// Where appends a list predicates to the PasswordItemUpdate builder.
func (piu *PasswordItemUpdate) Where(ps ...predicate.PasswordItem) *PasswordItemUpdate {
	piu.mutation.Where(ps...)
	return piu
}

// SetUpdateTime sets the "update_time" field.
func (piu *PasswordItemUpdate) SetUpdateTime(t time.Time) *PasswordItemUpdate {
	piu.mutation.SetUpdateTime(t)
	return piu
}

// SetAvatar sets the "avatar" field.
func (piu *PasswordItemUpdate) SetAvatar(s string) *PasswordItemUpdate {
	piu.mutation.SetAvatar(s)
	return piu
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (piu *PasswordItemUpdate) SetNillableAvatar(s *string) *PasswordItemUpdate {
	if s != nil {
		piu.SetAvatar(*s)
	}
	return piu
}

// ClearAvatar clears the value of the "avatar" field.
func (piu *PasswordItemUpdate) ClearAvatar() *PasswordItemUpdate {
	piu.mutation.ClearAvatar()
	return piu
}

// SetDescription sets the "description" field.
func (piu *PasswordItemUpdate) SetDescription(s string) *PasswordItemUpdate {
	piu.mutation.SetDescription(s)
	return piu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (piu *PasswordItemUpdate) SetNillableDescription(s *string) *PasswordItemUpdate {
	if s != nil {
		piu.SetDescription(*s)
	}
	return piu
}

// ClearDescription clears the value of the "description" field.
func (piu *PasswordItemUpdate) ClearDescription() *PasswordItemUpdate {
	piu.mutation.ClearDescription()
	return piu
}

// SetSiteName sets the "site_name" field.
func (piu *PasswordItemUpdate) SetSiteName(s string) *PasswordItemUpdate {
	piu.mutation.SetSiteName(s)
	return piu
}

// SetNillableSiteName sets the "site_name" field if the given value is not nil.
func (piu *PasswordItemUpdate) SetNillableSiteName(s *string) *PasswordItemUpdate {
	if s != nil {
		piu.SetSiteName(*s)
	}
	return piu
}

// ClearSiteName clears the value of the "site_name" field.
func (piu *PasswordItemUpdate) ClearSiteName() *PasswordItemUpdate {
	piu.mutation.ClearSiteName()
	return piu
}

// SetSiteURL sets the "site_url" field.
func (piu *PasswordItemUpdate) SetSiteURL(s string) *PasswordItemUpdate {
	piu.mutation.SetSiteURL(s)
	return piu
}

// SetNillableSiteURL sets the "site_url" field if the given value is not nil.
func (piu *PasswordItemUpdate) SetNillableSiteURL(s *string) *PasswordItemUpdate {
	if s != nil {
		piu.SetSiteURL(*s)
	}
	return piu
}

// ClearSiteURL clears the value of the "site_url" field.
func (piu *PasswordItemUpdate) ClearSiteURL() *PasswordItemUpdate {
	piu.mutation.ClearSiteURL()
	return piu
}

// SetUsername sets the "username" field.
func (piu *PasswordItemUpdate) SetUsername(s string) *PasswordItemUpdate {
	piu.mutation.SetUsername(s)
	return piu
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (piu *PasswordItemUpdate) SetNillableUsername(s *string) *PasswordItemUpdate {
	if s != nil {
		piu.SetUsername(*s)
	}
	return piu
}

// ClearUsername clears the value of the "username" field.
func (piu *PasswordItemUpdate) ClearUsername() *PasswordItemUpdate {
	piu.mutation.ClearUsername()
	return piu
}

// SetUsernameType sets the "username_type" field.
func (piu *PasswordItemUpdate) SetUsernameType(s string) *PasswordItemUpdate {
	piu.mutation.SetUsernameType(s)
	return piu
}

// SetNillableUsernameType sets the "username_type" field if the given value is not nil.
func (piu *PasswordItemUpdate) SetNillableUsernameType(s *string) *PasswordItemUpdate {
	if s != nil {
		piu.SetUsernameType(*s)
	}
	return piu
}

// ClearUsernameType clears the value of the "username_type" field.
func (piu *PasswordItemUpdate) ClearUsernameType() *PasswordItemUpdate {
	piu.mutation.ClearUsernameType()
	return piu
}

// SetPassword sets the "password" field.
func (piu *PasswordItemUpdate) SetPassword(s string) *PasswordItemUpdate {
	piu.mutation.SetPassword(s)
	return piu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (piu *PasswordItemUpdate) SetNillablePassword(s *string) *PasswordItemUpdate {
	if s != nil {
		piu.SetPassword(*s)
	}
	return piu
}

// ClearPassword clears the value of the "password" field.
func (piu *PasswordItemUpdate) ClearPassword() *PasswordItemUpdate {
	piu.mutation.ClearPassword()
	return piu
}

// SetTags sets the "tags" field.
func (piu *PasswordItemUpdate) SetTags(s []string) *PasswordItemUpdate {
	piu.mutation.SetTags(s)
	return piu
}

// AppendTags appends s to the "tags" field.
func (piu *PasswordItemUpdate) AppendTags(s []string) *PasswordItemUpdate {
	piu.mutation.AppendTags(s)
	return piu
}

// ClearTags clears the value of the "tags" field.
func (piu *PasswordItemUpdate) ClearTags() *PasswordItemUpdate {
	piu.mutation.ClearTags()
	return piu
}

// Mutation returns the PasswordItemMutation object of the builder.
func (piu *PasswordItemUpdate) Mutation() *PasswordItemMutation {
	return piu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (piu *PasswordItemUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	piu.defaults()
	if len(piu.hooks) == 0 {
		affected, err = piu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PasswordItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			piu.mutation = mutation
			affected, err = piu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(piu.hooks) - 1; i >= 0; i-- {
			if piu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = piu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, piu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (piu *PasswordItemUpdate) SaveX(ctx context.Context) int {
	affected, err := piu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (piu *PasswordItemUpdate) Exec(ctx context.Context) error {
	_, err := piu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (piu *PasswordItemUpdate) ExecX(ctx context.Context) {
	if err := piu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (piu *PasswordItemUpdate) defaults() {
	if _, ok := piu.mutation.UpdateTime(); !ok {
		v := passworditem.UpdateDefaultUpdateTime()
		piu.mutation.SetUpdateTime(v)
	}
}

func (piu *PasswordItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   passworditem.Table,
			Columns: passworditem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: passworditem.FieldID,
			},
		},
	}
	if ps := piu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := piu.mutation.UpdateTime(); ok {
		_spec.SetField(passworditem.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := piu.mutation.Avatar(); ok {
		_spec.SetField(passworditem.FieldAvatar, field.TypeString, value)
	}
	if piu.mutation.AvatarCleared() {
		_spec.ClearField(passworditem.FieldAvatar, field.TypeString)
	}
	if value, ok := piu.mutation.Description(); ok {
		_spec.SetField(passworditem.FieldDescription, field.TypeString, value)
	}
	if piu.mutation.DescriptionCleared() {
		_spec.ClearField(passworditem.FieldDescription, field.TypeString)
	}
	if value, ok := piu.mutation.SiteName(); ok {
		_spec.SetField(passworditem.FieldSiteName, field.TypeString, value)
	}
	if piu.mutation.SiteNameCleared() {
		_spec.ClearField(passworditem.FieldSiteName, field.TypeString)
	}
	if value, ok := piu.mutation.SiteURL(); ok {
		_spec.SetField(passworditem.FieldSiteURL, field.TypeString, value)
	}
	if piu.mutation.SiteURLCleared() {
		_spec.ClearField(passworditem.FieldSiteURL, field.TypeString)
	}
	if value, ok := piu.mutation.Username(); ok {
		_spec.SetField(passworditem.FieldUsername, field.TypeString, value)
	}
	if piu.mutation.UsernameCleared() {
		_spec.ClearField(passworditem.FieldUsername, field.TypeString)
	}
	if value, ok := piu.mutation.UsernameType(); ok {
		_spec.SetField(passworditem.FieldUsernameType, field.TypeString, value)
	}
	if piu.mutation.UsernameTypeCleared() {
		_spec.ClearField(passworditem.FieldUsernameType, field.TypeString)
	}
	if value, ok := piu.mutation.Password(); ok {
		_spec.SetField(passworditem.FieldPassword, field.TypeString, value)
	}
	if piu.mutation.PasswordCleared() {
		_spec.ClearField(passworditem.FieldPassword, field.TypeString)
	}
	if value, ok := piu.mutation.Tags(); ok {
		_spec.SetField(passworditem.FieldTags, field.TypeJSON, value)
	}
	if value, ok := piu.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, passworditem.FieldTags, value)
		})
	}
	if piu.mutation.TagsCleared() {
		_spec.ClearField(passworditem.FieldTags, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, piu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passworditem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// PasswordItemUpdateOne is the builder for updating a single PasswordItem entity.
type PasswordItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PasswordItemMutation
}

// SetUpdateTime sets the "update_time" field.
func (piuo *PasswordItemUpdateOne) SetUpdateTime(t time.Time) *PasswordItemUpdateOne {
	piuo.mutation.SetUpdateTime(t)
	return piuo
}

// SetAvatar sets the "avatar" field.
func (piuo *PasswordItemUpdateOne) SetAvatar(s string) *PasswordItemUpdateOne {
	piuo.mutation.SetAvatar(s)
	return piuo
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (piuo *PasswordItemUpdateOne) SetNillableAvatar(s *string) *PasswordItemUpdateOne {
	if s != nil {
		piuo.SetAvatar(*s)
	}
	return piuo
}

// ClearAvatar clears the value of the "avatar" field.
func (piuo *PasswordItemUpdateOne) ClearAvatar() *PasswordItemUpdateOne {
	piuo.mutation.ClearAvatar()
	return piuo
}

// SetDescription sets the "description" field.
func (piuo *PasswordItemUpdateOne) SetDescription(s string) *PasswordItemUpdateOne {
	piuo.mutation.SetDescription(s)
	return piuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (piuo *PasswordItemUpdateOne) SetNillableDescription(s *string) *PasswordItemUpdateOne {
	if s != nil {
		piuo.SetDescription(*s)
	}
	return piuo
}

// ClearDescription clears the value of the "description" field.
func (piuo *PasswordItemUpdateOne) ClearDescription() *PasswordItemUpdateOne {
	piuo.mutation.ClearDescription()
	return piuo
}

// SetSiteName sets the "site_name" field.
func (piuo *PasswordItemUpdateOne) SetSiteName(s string) *PasswordItemUpdateOne {
	piuo.mutation.SetSiteName(s)
	return piuo
}

// SetNillableSiteName sets the "site_name" field if the given value is not nil.
func (piuo *PasswordItemUpdateOne) SetNillableSiteName(s *string) *PasswordItemUpdateOne {
	if s != nil {
		piuo.SetSiteName(*s)
	}
	return piuo
}

// ClearSiteName clears the value of the "site_name" field.
func (piuo *PasswordItemUpdateOne) ClearSiteName() *PasswordItemUpdateOne {
	piuo.mutation.ClearSiteName()
	return piuo
}

// SetSiteURL sets the "site_url" field.
func (piuo *PasswordItemUpdateOne) SetSiteURL(s string) *PasswordItemUpdateOne {
	piuo.mutation.SetSiteURL(s)
	return piuo
}

// SetNillableSiteURL sets the "site_url" field if the given value is not nil.
func (piuo *PasswordItemUpdateOne) SetNillableSiteURL(s *string) *PasswordItemUpdateOne {
	if s != nil {
		piuo.SetSiteURL(*s)
	}
	return piuo
}

// ClearSiteURL clears the value of the "site_url" field.
func (piuo *PasswordItemUpdateOne) ClearSiteURL() *PasswordItemUpdateOne {
	piuo.mutation.ClearSiteURL()
	return piuo
}

// SetUsername sets the "username" field.
func (piuo *PasswordItemUpdateOne) SetUsername(s string) *PasswordItemUpdateOne {
	piuo.mutation.SetUsername(s)
	return piuo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (piuo *PasswordItemUpdateOne) SetNillableUsername(s *string) *PasswordItemUpdateOne {
	if s != nil {
		piuo.SetUsername(*s)
	}
	return piuo
}

// ClearUsername clears the value of the "username" field.
func (piuo *PasswordItemUpdateOne) ClearUsername() *PasswordItemUpdateOne {
	piuo.mutation.ClearUsername()
	return piuo
}

// SetUsernameType sets the "username_type" field.
func (piuo *PasswordItemUpdateOne) SetUsernameType(s string) *PasswordItemUpdateOne {
	piuo.mutation.SetUsernameType(s)
	return piuo
}

// SetNillableUsernameType sets the "username_type" field if the given value is not nil.
func (piuo *PasswordItemUpdateOne) SetNillableUsernameType(s *string) *PasswordItemUpdateOne {
	if s != nil {
		piuo.SetUsernameType(*s)
	}
	return piuo
}

// ClearUsernameType clears the value of the "username_type" field.
func (piuo *PasswordItemUpdateOne) ClearUsernameType() *PasswordItemUpdateOne {
	piuo.mutation.ClearUsernameType()
	return piuo
}

// SetPassword sets the "password" field.
func (piuo *PasswordItemUpdateOne) SetPassword(s string) *PasswordItemUpdateOne {
	piuo.mutation.SetPassword(s)
	return piuo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (piuo *PasswordItemUpdateOne) SetNillablePassword(s *string) *PasswordItemUpdateOne {
	if s != nil {
		piuo.SetPassword(*s)
	}
	return piuo
}

// ClearPassword clears the value of the "password" field.
func (piuo *PasswordItemUpdateOne) ClearPassword() *PasswordItemUpdateOne {
	piuo.mutation.ClearPassword()
	return piuo
}

// SetTags sets the "tags" field.
func (piuo *PasswordItemUpdateOne) SetTags(s []string) *PasswordItemUpdateOne {
	piuo.mutation.SetTags(s)
	return piuo
}

// AppendTags appends s to the "tags" field.
func (piuo *PasswordItemUpdateOne) AppendTags(s []string) *PasswordItemUpdateOne {
	piuo.mutation.AppendTags(s)
	return piuo
}

// ClearTags clears the value of the "tags" field.
func (piuo *PasswordItemUpdateOne) ClearTags() *PasswordItemUpdateOne {
	piuo.mutation.ClearTags()
	return piuo
}

// Mutation returns the PasswordItemMutation object of the builder.
func (piuo *PasswordItemUpdateOne) Mutation() *PasswordItemMutation {
	return piuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (piuo *PasswordItemUpdateOne) Select(field string, fields ...string) *PasswordItemUpdateOne {
	piuo.fields = append([]string{field}, fields...)
	return piuo
}

// Save executes the query and returns the updated PasswordItem entity.
func (piuo *PasswordItemUpdateOne) Save(ctx context.Context) (*PasswordItem, error) {
	var (
		err  error
		node *PasswordItem
	)
	piuo.defaults()
	if len(piuo.hooks) == 0 {
		node, err = piuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PasswordItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			piuo.mutation = mutation
			node, err = piuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(piuo.hooks) - 1; i >= 0; i-- {
			if piuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = piuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, piuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PasswordItem)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PasswordItemMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (piuo *PasswordItemUpdateOne) SaveX(ctx context.Context) *PasswordItem {
	node, err := piuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (piuo *PasswordItemUpdateOne) Exec(ctx context.Context) error {
	_, err := piuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (piuo *PasswordItemUpdateOne) ExecX(ctx context.Context) {
	if err := piuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (piuo *PasswordItemUpdateOne) defaults() {
	if _, ok := piuo.mutation.UpdateTime(); !ok {
		v := passworditem.UpdateDefaultUpdateTime()
		piuo.mutation.SetUpdateTime(v)
	}
}

func (piuo *PasswordItemUpdateOne) sqlSave(ctx context.Context) (_node *PasswordItem, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   passworditem.Table,
			Columns: passworditem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: passworditem.FieldID,
			},
		},
	}
	id, ok := piuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PasswordItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := piuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, passworditem.FieldID)
		for _, f := range fields {
			if !passworditem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != passworditem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := piuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := piuo.mutation.UpdateTime(); ok {
		_spec.SetField(passworditem.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := piuo.mutation.Avatar(); ok {
		_spec.SetField(passworditem.FieldAvatar, field.TypeString, value)
	}
	if piuo.mutation.AvatarCleared() {
		_spec.ClearField(passworditem.FieldAvatar, field.TypeString)
	}
	if value, ok := piuo.mutation.Description(); ok {
		_spec.SetField(passworditem.FieldDescription, field.TypeString, value)
	}
	if piuo.mutation.DescriptionCleared() {
		_spec.ClearField(passworditem.FieldDescription, field.TypeString)
	}
	if value, ok := piuo.mutation.SiteName(); ok {
		_spec.SetField(passworditem.FieldSiteName, field.TypeString, value)
	}
	if piuo.mutation.SiteNameCleared() {
		_spec.ClearField(passworditem.FieldSiteName, field.TypeString)
	}
	if value, ok := piuo.mutation.SiteURL(); ok {
		_spec.SetField(passworditem.FieldSiteURL, field.TypeString, value)
	}
	if piuo.mutation.SiteURLCleared() {
		_spec.ClearField(passworditem.FieldSiteURL, field.TypeString)
	}
	if value, ok := piuo.mutation.Username(); ok {
		_spec.SetField(passworditem.FieldUsername, field.TypeString, value)
	}
	if piuo.mutation.UsernameCleared() {
		_spec.ClearField(passworditem.FieldUsername, field.TypeString)
	}
	if value, ok := piuo.mutation.UsernameType(); ok {
		_spec.SetField(passworditem.FieldUsernameType, field.TypeString, value)
	}
	if piuo.mutation.UsernameTypeCleared() {
		_spec.ClearField(passworditem.FieldUsernameType, field.TypeString)
	}
	if value, ok := piuo.mutation.Password(); ok {
		_spec.SetField(passworditem.FieldPassword, field.TypeString, value)
	}
	if piuo.mutation.PasswordCleared() {
		_spec.ClearField(passworditem.FieldPassword, field.TypeString)
	}
	if value, ok := piuo.mutation.Tags(); ok {
		_spec.SetField(passworditem.FieldTags, field.TypeJSON, value)
	}
	if value, ok := piuo.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, passworditem.FieldTags, value)
		})
	}
	if piuo.mutation.TagsCleared() {
		_spec.ClearField(passworditem.FieldTags, field.TypeJSON)
	}
	_node = &PasswordItem{config: piuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, piuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passworditem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
