// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/riadafridishibly/vault-app/ent/passworditem"
	"github.com/riadafridishibly/vault-app/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	passworditemFields := schema.PasswordItem{}.Fields()
	_ = passworditemFields
	// passworditemDescCreatedAt is the schema descriptor for created_at field.
	passworditemDescCreatedAt := passworditemFields[8].Descriptor()
	// passworditem.DefaultCreatedAt holds the default value on creation for the created_at field.
	passworditem.DefaultCreatedAt = passworditemDescCreatedAt.Default.(func() time.Time)
	// passworditemDescUpdatedAt is the schema descriptor for updated_at field.
	passworditemDescUpdatedAt := passworditemFields[9].Descriptor()
	// passworditem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	passworditem.DefaultUpdatedAt = passworditemDescUpdatedAt.Default.(func() time.Time)
}
