// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPasswordBreach(arg1) {
  return window['go']['main']['App']['CheckPasswordBreach'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function GenerateNewPassword(arg1, arg2) {
  return window['go']['main']['App']['GenerateNewPassword'](arg1, arg2);
}

export function GenerateRandomPassword(arg1) {
  return window['go']['main']['App']['GenerateRandomPassword'](arg1);
}

export function GetAddress() {
  return window['go']['main']['App']['GetAddress']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDialog() {
  return window['go']['main']['App']['OpenDialog']();
}

export function PasteFromClipboard() {
  return window['go']['main']['App']['PasteFromClipboard']();
}
