// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Copy(arg1) {
  return window['go']['main']['ClipboardService']['Copy'](arg1);
}

export function Paste() {
  return window['go']['main']['ClipboardService']['Paste']();
}
