// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1) {
  return window['go']['main']['DatabaseService']['CreateFile'](arg1);
}

export function CreateKey() {
  return window['go']['main']['DatabaseService']['CreateKey']();
}

export function CreatePasswordItem(arg1) {
  return window['go']['main']['DatabaseService']['CreatePasswordItem'](arg1);
}

export function DeleteFileByID(arg1) {
  return window['go']['main']['DatabaseService']['DeleteFileByID'](arg1);
}

export function DeleteKeyByID(arg1) {
  return window['go']['main']['DatabaseService']['DeleteKeyByID'](arg1);
}

export function DeletePasswordItem(arg1) {
  return window['go']['main']['DatabaseService']['DeletePasswordItem'](arg1);
}

export function ReadAllFiles() {
  return window['go']['main']['DatabaseService']['ReadAllFiles']();
}

export function ReadAllKeys() {
  return window['go']['main']['DatabaseService']['ReadAllKeys']();
}

export function ReadAllPasswordItems() {
  return window['go']['main']['DatabaseService']['ReadAllPasswordItems']();
}

export function ReadSingleFile(arg1) {
  return window['go']['main']['DatabaseService']['ReadSingleFile'](arg1);
}

export function ReadSingleKey(arg1) {
  return window['go']['main']['DatabaseService']['ReadSingleKey'](arg1);
}

export function ReadSinglePasswordItems(arg1) {
  return window['go']['main']['DatabaseService']['ReadSinglePasswordItems'](arg1);
}

export function UpdatePasswordItem(arg1) {
  return window['go']['main']['DatabaseService']['UpdatePasswordItem'](arg1);
}
