// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dao} from '../models';

export function CreatePasswordItem(arg1:dao.PasswordItem):Promise<Error>;
