// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ent} from '../models';

export function CreatePasswordItem(arg1:ent.PasswordItem):Promise<ent.PasswordItem>;

export function DeletePasswordItem(arg1:number):Promise<ent.PasswordItem>;

export function ReadAllPasswordItems():Promise<Array<ent.PasswordItem>>;

export function ReadSinglePasswordItems(arg1:number):Promise<ent.PasswordItem>;

export function UpdatePasswordItem(arg1:ent.PasswordItem):Promise<ent.PasswordItem>;
