// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPasswordBreach(arg1) {
  return window['go']['main']['PasswordService']['CheckPasswordBreach'](arg1);
}

export function GeneratePassword(arg1) {
  return window['go']['main']['PasswordService']['GeneratePassword'](arg1);
}
