// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsUserExist() {
  return window['go']['main']['UserService']['IsUserExist']();
}

export function IsUserLoggedIn() {
  return window['go']['main']['UserService']['IsUserLoggedIn']();
}

export function Login(arg1) {
  return window['go']['main']['UserService']['Login'](arg1);
}

export function Register(arg1) {
  return window['go']['main']['UserService']['Register'](arg1);
}
