// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Key is the predicate function for key builders.
type Key func(*sql.Selector)

// PasswordItem is the predicate function for passworditem builders.
type PasswordItem func(*sql.Selector)
